# Generated by Django 5.0.7 on 2024-08-01 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flightApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="flight",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="flightApp.flight"
            ),
        ),
    ]
